"""Exact measured live suite inventory shared by both receipt assemblers."""

from __future__ import annotations

from typing import Any


SUITES: dict[str, dict[str, Any]] = {
    "mysql_catalog": {
        "test": "p4_live_catalog_fixture_proves_pages_caps_permissions_and_cli",
        "cases": {
            "mysql.catalog.cli.page1",
            "mysql.catalog.cli.page2",
            "mysql.catalog.column.ordinal_order",
            "mysql.catalog.column.page1",
            "mysql.catalog.column.page2",
            "mysql.catalog.count_cap",
            "mysql.catalog.empty",
            "mysql.catalog.filter.clear_after_metadata_cap",
            "mysql.catalog.filter.narrow_after_count_cap",
            "mysql.catalog.metadata_cap_4mib",
            "mysql.catalog.permission.check_denied",
            "mysql.catalog.permission.execute_denied",
            "mysql.catalog.relation.binary_order",
            "mysql.catalog.relation.page1",
            "mysql.catalog.relation.page2",
            "mysql.catalog.relation.table",
            "mysql.catalog.relation.view",
            "mysql.catalog.schema.scope",
            "mysql.catalog.schema.visibility",
            "mysql.catalog.token.cross_config_rejected",
            "mysql.catalog.token.stale_connection_rejected",
            "mysql.catalog.token.stale_generation_rejected",
            "mysql.catalog.token.tampered_rejected",
        },
        "measurements": {
            "cli_pages": (2, None),
            "column_pages": (2, None),
            "column_rows": (100, None),
            "denied_operations": (2, None),
            "metadata_retained_bytes": (1, 4 * 1024 * 1024),
            "metadata_truncations": (1, None),
            "relation_pages": (2, None),
            "relation_rows": (34, None),
            "retained_relations": (2_000, 2_000),
        },
    },
    "mysql_safety": {
        "test": "live_mysql_safety_receipt",
        "cases": {
            "mysql.auth.environment.available.correct",
            "mysql.auth.environment.available.wrong",
            "mysql.auth.environment.available.wrong.action",
            "mysql.auth.environment.available.wrong.code",
            "mysql.auth.environment.available.wrong.recovery",
            "mysql.auth.environment.empty",
            "mysql.auth.environment.empty.action",
            "mysql.auth.environment.empty.code",
            "mysql.auth.environment.empty.recovery",
            "mysql.auth.environment.missing",
            "mysql.auth.environment.missing.action",
            "mysql.auth.environment.missing.code",
            "mysql.auth.environment.missing.recovery",
            "mysql.auth.session.correct",
            "mysql.auth.session.wrong",
            "mysql.auth.session.wrong.action",
            "mysql.auth.session.wrong.code",
            "mysql.auth.session.wrong.recovery",
            "mysql.execute.read",
            "mysql.marker.current_target.extracted_prepared",
            "mysql.marker.explicit_selection.absent",
            "mysql.marker.explicit_selection.driver_denied",
            "mysql.marker.explicit_selection.ui_rejected",
            "mysql.marker.second_probe.absent",
            "mysql.marker.second_probe.driver_denied",
            "mysql.read_lease.mutation_denied",
            "mysql.read_lease.no_raw_fallback",
            "mysql.read_lease.non_select_denied",
            "mysql.read_lease.server_side_effect_absent",
            "mysql.read_lease.server_side_effect_denied",
            "mysql.read_lease.session_retained",
            "mysql.read_lease.static_recovery",
        },
        "measurements": {
            "auth_failures": (4, None),
            "marker_denied_attempts": (2, 2),
            "marker_rows_after": (0, 0),
            "non_select_denied_attempts": (1, None),
            "raw_fallback_attempts": (0, 0),
            "server_side_effect_denied_attempts": (1, 1),
            "statements_executed": (8, 8),
        },
    },
    "redis": {
        "test": "redis_live_receipt",
        "cases": {
            "redis.auth.plaintext.environment.available.correct",
            "redis.auth.plaintext.environment.available.wrong",
            "redis.auth.plaintext.environment.available.wrong.action",
            "redis.auth.plaintext.environment.available.wrong.code",
            "redis.auth.plaintext.environment.available.wrong.recovery",
            "redis.auth.plaintext.environment.empty",
            "redis.auth.plaintext.environment.empty.action",
            "redis.auth.plaintext.environment.empty.code",
            "redis.auth.plaintext.environment.empty.recovery",
            "redis.auth.plaintext.environment.missing",
            "redis.auth.plaintext.environment.missing.action",
            "redis.auth.plaintext.environment.missing.code",
            "redis.auth.plaintext.environment.missing.recovery",
            "redis.auth.plaintext.session.correct",
            "redis.auth.plaintext.session.wrong",
            "redis.auth.plaintext.session.wrong.action",
            "redis.auth.plaintext.session.wrong.code",
            "redis.auth.plaintext.session.wrong.recovery",
            "redis.auth.tls.environment.available.correct",
            "redis.auth.tls.environment.available.wrong",
            "redis.auth.tls.environment.available.wrong.action",
            "redis.auth.tls.environment.available.wrong.code",
            "redis.auth.tls.environment.available.wrong.recovery",
            "redis.auth.tls.environment.empty",
            "redis.auth.tls.environment.empty.action",
            "redis.auth.tls.environment.empty.code",
            "redis.auth.tls.environment.empty.recovery",
            "redis.auth.tls.environment.missing",
            "redis.auth.tls.environment.missing.action",
            "redis.auth.tls.environment.missing.code",
            "redis.auth.tls.environment.missing.recovery",
            "redis.auth.tls.session.correct",
            "redis.auth.tls.session.wrong",
            "redis.auth.tls.session.wrong.action",
            "redis.auth.tls.session.wrong.code",
            "redis.auth.tls.session.wrong.recovery",
            "redis.classifier.no_command",
            "redis.cli.browse",
            "redis.cli.inspect",
            "redis.inspect.truncation_64kib",
            "redis.inspect.ttl.expiring",
            "redis.inspect.ttl.missing",
            "redis.inspect.ttl.persistent",
            "redis.inspect.type.hash",
            "redis.inspect.type.list",
            "redis.inspect.type.set",
            "redis.inspect.type.stream",
            "redis.inspect.type.string",
            "redis.inspect.type.zset",
            "redis.mutation.readback",
            "redis.scan.multiple_pages",
            "redis.scan.oversize_skipped",
            "redis.scan.raw_binary_identity",
            "redis.tls.ca_preserved",
            "redis.tls.host_recovery",
            "redis.tls.wrong_ca.action",
            "redis.tls.wrong_ca.code",
            "redis.tls.wrong_ca.focus_ca",
            "redis.tls.wrong_host.action",
            "redis.tls.wrong_host.code",
            "redis.tls.wrong_host.focus_host",
        },
        "measurements": {
            "auth_failures": (8, None),
            "cli_operations": (2, None),
            "inspect_types": (6, 6),
            "mutation_readbacks": (2, None),
            "plaintext_fallback_attempts": (0, 0),
            "required_tls_attempts": (3, None),
            "scan_pages": (2, None),
            "tls_recovery_attempts": (1, None),
        },
    },
}
